[package]
name = "usbd-ccid"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apdu-dispatch = { path = "../apdu-dispatch" }
asn1derpy = "0.1.0"
delog = "0.1.0-alpha.3"
heapless = "0.5.6"
heapless-bytes = "0.1.1"
interchange = "0.1.0"
iso7816 = { path = "../iso7816" }
usb-device = { version = "0.2.3", features = ["control-buffer-256"] }

[features]
default = []
highspeed-usb = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
